x-app: &default-app
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true
  healthcheck:
    interval: "60s"
    timeout: "3s"
    start_period: "5s"
    retries: 3

services:
  server:
    <<: *default-app
    # depends_on:
    # - "backend"
    build:
      context: "./services/server"
      target: ${NODE_ENV}
      dockerfile: Dockerfile
      args:
        - "NODE_ENV=${NODE_ENV}"
        - "SERVER_PORT=${SERVER_PORT}"
        - "CLIENT_PORT=${CLIENT_PORT}"
        - "CLIENT_HOST=${CLIENT_HOST}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    healthcheck:
      test: "${DOCKER_CLIENT_HEALTHCHECK_TEST}"
    volumes:
      - "./services/server:/node/app:delegated" # Delegated = Performance improvement for files on MAC
      - "/node/app/node_modules"
  client:
    <<: *default-app
    # depends_on:
    # - "backend"
    build:
      context: "./services/client"
      target: ${NODE_ENV}
      dockerfile: Dockerfile
      args:
        - "NODE_ENV=${NODE_ENV}"
        - "CLIENT_PORT=${CLIENT_PORT}"
        - "CLIENT_HOST_=${CLIENT_HOST}"
        - "SERVER_PORT=${SERVER_PORT}"
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    healthcheck:
      test: "${DOCKER_CLIENT_HEALTHCHECK_TEST}"
    volumes:
      - "./services/client:/node/app:delegated" # Delegated = Performance improvement for files on MAC
      - "/node/app/node_modules" # Anonymous volume to hide our local node_modules
